platform :ios, '5.0'

target :xiaoshuoyuedu, :exclusive => true do
  pod 'AFNetworking', '~> 1.3.0'
  pod 'MSNavigationPaneViewController', '~> 0.2.0'
  pod 'MBProgressHUD', '~> 0.6'
  pod 'WTURLImageView', '~> 1.1.0'
  pod 'CKRefreshControl', '~> 1.1.0'
  pod 'FMDB', '~> 2.1'
  pod 'GSBookShelf', '~> 0.0.1'
  pod 'CustomBadge', '~> 2.0'
  pod 'WEPopover', '~> 0.0.1'
  pod 'ViewDeck', '~> 2.2.11'
  pod 'QBKOverlayMenuView', '~> 0.0.1'
end
