platform :ios, '5.0'

target :xiaoshuoyuedu, :exclusive => true do
  pod 'AFNetworking', '~> 1.3.0'
  pod 'JSONKit',  '~> 1.5pre'
  pod 'MSNavigationPaneViewController', '~> 0.2.0'
  pod 'MBProgressHUD', '~> 0.6'
  pod 'WTURLImageView', '~> 1.1.0'
  pod 'CKRefreshControl', '~> 1.1.0'
  pod 'FMDB', '~> 2.1'
end
